# Generated by Django 2.0.8 on 2018-09-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuites', '0003_tuite_liked_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuite',
            options={'ordering': ('-date_created',)},
        ),
    ]
